/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Emilio Delgado",
  "tagline": "PhD research · LLM-generated code quality · Specification-Driven Development",
  "url": "https://emi-dm.github.io",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenAnchors": "ignore",
  "favicon": "https://intia.unex.es/favicon.ico",
  "stylesheets": [
    "https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@300;400;600&family=DM+Sans:wght@400;500;700&family=JetBrains+Mono:wght@400;500&display=swap"
  ],
  "organizationName": "emi-dm",
  "projectName": "emi-dm.github.io",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "documentation",
          "routeBasePath": "docs",
          "sidebarPath": "/Users/emi/Desktop/emi-dm.github.io/sidebars.ts",
          "editUrl": "https://github.com/emi-dm/emi-dm.github.io/tree/main/documentation/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/emi-dm/emi-dm.github.io/tree/main/blog/",
          "authorsMapPath": "/Users/emi/Desktop/emi-dm.github.io/authors.json"
        },
        "theme": {
          "customCss": "/Users/emi/Desktop/emi-dm.github.io/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "EMILIO.DELGADO",
      "items": [
        {
          "to": "/",
          "label": "Home",
          "position": "left"
        },
        {
          "to": "/#about",
          "label": "About",
          "position": "left"
        },
        {
          "to": "/#timeline",
          "label": "Journey",
          "position": "left"
        },
        {
          "to": "/#research",
          "label": "Research",
          "position": "left"
        },
        {
          "to": "/#projects",
          "label": "Projects",
          "position": "left"
        },
        {
          "to": "/#repositories",
          "label": "Repositories",
          "position": "left"
        },
        {
          "to": "/#publications",
          "label": "Publications",
          "position": "left"
        },
        {
          "to": "/docs/intro",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://github.com/emi-dm",
          "label": "GitHub",
          "position": "right",
          "target": "_blank",
          "rel": "noopener noreferrer"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Research",
          "items": [
            {
              "label": "INTIA",
              "href": "https://intia.unex.es/",
              "target": "_blank",
              "rel": "noopener noreferrer"
            },
            {
              "label": "i3Lab",
              "href": "https://i3lab.unex.es/",
              "target": "_blank",
              "rel": "noopener noreferrer"
            },
            {
              "label": "Google Scholar",
              "href": "https://scholar.google.com/citations?user=eIBVkQEAAAAJ&hl=es",
              "target": "_blank",
              "rel": "noopener noreferrer"
            }
          ]
        },
        {
          "title": "Site",
          "items": [
            {
              "label": "Home",
              "to": "/"
            },
            {
              "label": "Docs",
              "to": "/docs/intro"
            },
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/emi-dm",
              "target": "_blank",
              "rel": "noopener noreferrer"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Emilio Delgado"
    },
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
